use_frameworks!

platform :ios, '9.0'

target 'TWDatePicker_Example' do
  pod 'TWDatePicker', :path => '../'

  target 'TWDatePicker_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
